apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-service
  template:
    metadata:
      labels:
        app: llm-service
    spec:
      containers:
      - name: llm-service
        image: bitslasher1003/stock-llm-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: stock-secrets
              key: gemini-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  labels:
    app: llm-service
spec:
  selector:
    app: llm-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
